### PR TITLE
check_results updates work dir

### PR DESCRIPTION
**Pull request by dpellegr**
In make_job_work_string there is a formatting problem to be looked into. Currently it only works with integers angles and amplitudes.

### CODE REVIEW

**Comment by rdemaria** [comment]
Have you tried %g for formatting? The are examples of correct string handling in the code already. Alessio has also a study to test non integer strings

**Comment by dpellegr** [comment]
The %g formatting looks ok for generating the strings for the work directory. However checking on Alessio's test case I got additional floating point issues like the following one:

```
Check missing results
(23, 'simul', 62.275, 60.283, 11.664000000000001, 13.330000000000002, 'e5', 37.89473684210526) missing

```
These generate deeper into sixdb, but of course they affect the manipulation of the work folder, as many completed studies are reported as missing. To be looked into...

**Comment by rdemaria** [comment]
try something like %.9g

**Comment by amereghe** [comment]
in the corresponding piece of code in sixdesk (though in python) we have a simple print statement:
https://github.com/amereghe/SixDesk/blob/isolateScripts/utilities/python/generate_floats.py

**Comment by rdemaria** [comment]
I agree, indeed both "%.15g" and "%s" produce 11.664 applied to 11.664000000000001

**Comment by dpellegr** [comment]
There is no formatting done in check_completed_results() down to the database, therefore I am not sure about where to put these extra %g. The best place is probably in the creation of the DB, no?

This is pretty bad with Alessio's test case: _all_ the jobs are reported as missing possibly due to these formatting issues.
```
Opened hllhc10BaseB1.db successfully
Check missing results
(23, 'simul', 62.275, 60.283, 11.664000000000001, 13.330000000000002, 'e5', 37.89473684210526) missing
(27, 'simul', 62.32600000000001, 60.339999999999996, 8.3320000000000007, 9.9980000000000011, 'e5', 28.421052631578945) missing
(26, 'simul', 62.32600000000001, 60.339999999999996, 8.3320000000000007, 9.9980000000000011, 'e5', 28.421052631578945) missing
(26, 'simul', 62.309000000000005, 60.321, 8.3320000000000007, 9.9980000000000011, 'e5', 4.7368421052631575) missing
(27, 'simul', 62.32600000000001, 60.339999999999996, 6.6660000000000004, 8.3320000000000007, 'e5', 4.7368421052631575) missing
(26, 'simul', 62.275, 60.283, 8.3320000000000007, 9.9980000000000011, 'e5', 14.210526315789473) missing
(26, 'simul', 62.275, 60.283, 5.0, 6.6660000000000004, 'e5', 4.7368421052631575) missing
(26, 'simul', 62.32600000000001, 60.339999999999996, 11.664000000000001, 13.330000000000002, 'e5', 23.684210526315788) missing
.
.
.
```

**Comment by rdemaria** [comment]
I am working on this. The problem is in get_tunes, get_amplitudes and get_angles. I solved the first two and  I am working on get_angles... stay tuned...

**Pull request merged**
